#!/bin/bash

# Lighttpd Web Server Installation Script
# Comprehensive installation with module support and security hardening
# Compatible with Ubuntu, Debian, CentOS, RHEL, and Fedora

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Global variables
LIGHTTPD_VERSION="1.4.76"  # Fallback version, will be updated dynamically
INSTALL_DIR="/opt/lighttpd"
CONFIG_DIR="/etc/lighttpd"
LOG_DIR="/var/log/lighttpd"
WEB_ROOT="/var/www/html"
BACKUP_DIR="/opt/lighttpd/backups"
LOG_FILE="/tmp/lighttpd-install.log"

# Module selections
FASTCGI_ENABLED=false
SSL_ENABLED=false
CACHE_ENABLED=false
PROXY_ENABLED=false
REWRITE_ENABLED=false
COMPRESS_ENABLED=false
SECDOWNLOAD_ENABLED=false
STATUS_ENABLED=false
ACCESSLOG_ENABLED=false
EVHOST_ENABLED=false

# OS Detection
detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS=$NAME
        VER=$VERSION_ID
    elif type lsb_release >/dev/null 2>&1; then
        OS=$(lsb_release -si)
        VER=$(lsb_release -sr)
    elif [[ -f /etc/lsb-release ]]; then
        . /etc/lsb-release
        OS=$DISTRIB_ID
        VER=$DISTRIB_RELEASE
    elif [[ -f /etc/debian_version ]]; then
        OS=Debian
        VER=$(cat /etc/debian_version)
    else
        OS=$(uname -s)
        VER=$(uname -r)
    fi
    
    echo -e "${CYAN}Detected OS: $OS $VER${NC}"
}

# Get latest Lighttpd version
get_lighttpd_version() {
    echo -e "${CYAN}Fetching latest Lighttpd version...${NC}"
    
    # Try to get latest version from Lighttpd download page
    LATEST_VERSION=$(curl -s "https://download.lighttpd.net/lighttpd/releases-1.4.x/" | \
        grep -oP 'lighttpd-\K[0-9]+\.[0-9]+\.[0-9]+' | \
        sort -V | tail -n1)
    
    # Update to latest version if fetch succeeded
    if [[ -n "$LATEST_VERSION" ]]; then
        LIGHTTPD_VERSION="$LATEST_VERSION"
        echo -e "${GREEN}Found latest version: $LIGHTTPD_VERSION${NC}"
    else
        echo -e "${YELLOW}Using fallback version: $LIGHTTPD_VERSION${NC}"
    fi
}

# Check if user is root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}This script must be run as root${NC}"
        exit 1
    fi
}

# Install dependencies
install_dependencies() {
    echo -e "${CYAN}Installing dependencies...${NC}"
    
    case "$OS" in
        "Ubuntu"* | "Debian"*)
            apt-get update
            apt-get install -y build-essential wget curl git \
                libpcre3-dev libssl-dev zlib1g-dev \
                libbrotli-dev libzip-dev liblua5.3-dev \
                libmysqlclient-dev libpq-dev \
                systemd systemd-sysv
            ;;
        "CentOS"* | "RHEL"* | "Fedora"*)
            yum update -y
            yum groupinstall -y "Development Tools"
            yum install -y wget curl git \
                pcre-devel openssl-devel zlib-devel \
                brotli-devel libzip-devel lua-devel \
                mysql-devel postgresql-devel \
                systemd systemd-sysv
            ;;
        *)
            echo -e "${RED}Unsupported OS: $OS${NC}"
            exit 1
            ;;
    esac
    
    echo -e "${GREEN}✓ Dependencies installed${NC}"
}

# Download and compile Lighttpd
install_lighttpd_core() {
    echo -e "${CYAN}Installing Lighttpd $LIGHTTPD_VERSION...${NC}"
    
    # Create installation directory
    mkdir -p "$INSTALL_DIR"
    cd /tmp
    
    # Download Lighttpd source
    if [[ ! -d "lighttpd-${LIGHTTPD_VERSION}" ]]; then
        wget "https://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-${LIGHTTPD_VERSION}.tar.gz"
        tar -xzf "lighttpd-${LIGHTTPD_VERSION}.tar.gz"
    fi
    
    cd "lighttpd-${LIGHTTPD_VERSION}"
    
    # Configure build
    ./configure \
        --prefix="$INSTALL_DIR" \
        --sysconfdir="$CONFIG_DIR" \
        --localstatedir="/var" \
        --with-openssl \
        --with-pcre \
        --with-zlib \
        --with-brotli \
        --with-lua \
        --with-mysql \
        --with-pgsql \
        --enable-shared \
        --enable-static
    
    # Compile and install
    make -j$(nproc)
    make install
    
    echo -e "${GREEN}✓ Lighttpd core installed${NC}"
}

# Create directories
create_directories() {
    echo -e "${CYAN}Creating directories...${NC}"
    
    mkdir -p "$CONFIG_DIR"/{conf-available,conf-enabled,vhosts}
    mkdir -p "$LOG_DIR"
    mkdir -p "$BACKUP_DIR"
    mkdir -p "$WEB_ROOT"
    mkdir -p /run/lighttpd
    
    echo -e "${GREEN}✓ Directories created${NC}"
}

# Create main configuration
create_main_config() {
    echo -e "${CYAN}Creating main configuration...${NC}"
    
    cat > "$CONFIG_DIR/lighttpd.conf" << 'EOF'
# Lighttpd Configuration File
# Generated by AutoInstalls Lighttpd Manager

# Server configuration
server.modules = (
    "mod_access",
    "mod_accesslog",
    "mod_alias",
    "mod_dirlisting",
    "mod_indexfile",
    "mod_staticfile"
)

# Basic server settings
server.port = 80
server.bind = "0.0.0.0"
server.username = "www-data"
server.groupname = "www-data"
server.document-root = "/var/www/html"
server.pid-file = "/run/lighttpd/lighttpd.pid"
server.errorlog = "/var/log/lighttpd/error.log"
server.event-handler = "linux-sysepoll"
server.max-fds = 2048
server.max-connections = 1024

# Directory listing
dir-listing.activate = "enable"
dir-listing.hide-dotfiles = "enable"
dir-listing.encoding = "utf-8"

# Index files
index-file.names = (
    "index.html",
    "index.htm",
    "index.php",
    "index.py",
    "index.rb"
)

# Static file handling
static-file.exclude-extensions = (
    ".php", ".pl", ".fcgi", ".scgi", ".cgi", ".rb", ".py", ".lua"
)

# MIME types
mimetype.assign = (
    ".html" => "text/html",
    ".htm" => "text/html",
    ".txt" => "text/plain",
    ".css" => "text/css",
    ".js" => "application/javascript",
    ".json" => "application/json",
    ".xml" => "application/xml",
    ".jpg" => "image/jpeg",
    ".jpeg" => "image/jpeg",
    ".png" => "image/png",
    ".gif" => "image/gif",
    ".ico" => "image/x-icon",
    ".svg" => "image/svg+xml",
    ".pdf" => "application/pdf",
    ".zip" => "application/zip",
    ".tar.gz" => "application/x-tgz",
    ".mp3" => "audio/mpeg",
    ".mp4" => "video/mp4"
)

# Include additional configurations
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include "$CONFIG_DIR/conf-enabled/*.conf"
include "$CONFIG_DIR/vhosts/*.conf"
EOF
    
    echo -e "${GREEN}✓ Main configuration created${NC}"
}

# Create systemd service
create_systemd_service() {
    echo -e "${CYAN}Creating systemd service...${NC}"
    
    cat > /etc/systemd/system/lighttpd.service << EOF
[Unit]
Description=Lighttpd Web Server
After=network.target

[Service]
Type=forking
PIDFile=/run/lighttpd/lighttpd.pid
ExecStartPre=/usr/bin/install -d -m 755 -o www-data -g www-data /run/lighttpd
ExecStart=$INSTALL_DIR/sbin/lighttpd -D -f $CONFIG_DIR/lighttpd.conf
ExecReload=/bin/kill -USR2 \$MAINPID
ExecStop=/bin/kill -SIGTERM \$MAINPID
Restart=always
RestartSec=5
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable lighttpd
    
    echo -e "${GREEN}✓ Systemd service created${NC}"
}

# Module configuration menu
configure_modules() {
    echo -e "${CYAN}Lighttpd Modules Configuration${NC}"
    echo -e "${CYAN}===============================${NC}"
    echo ""
    
    echo "Select modules to install:"
    echo "   1) FastCGI (PHP/Python/Ruby support)"
    echo "   2) SSL/TLS (HTTPS support)"
    echo "   3) ModCache (Caching system)"
    echo "   4) ModProxy (Reverse proxy)"
    echo "   5) ModRewrite (URL rewriting)"
    echo "   6) ModCompress (Compression)"
    echo "   7) ModSecDownload (Secure downloads)"
    echo "   8) ModStatus (Server status)"
    echo "   9) ModAccessLog (Enhanced logging)"
    echo "   10) ModEVHost (Enhanced virtual hosting)"
    echo "   11) Install all recommended modules"
    echo "   12) Skip modules"
    echo ""
    read -p "Select an option [1-12]: " module_choice
    
    case "$module_choice" in
        1)
            FASTCGI_ENABLED=true
            configure_fastcgi
            ;;
        2)
            SSL_ENABLED=true
            configure_ssl
            ;;
        3)
            CACHE_ENABLED=true
            configure_cache
            ;;
        4)
            PROXY_ENABLED=true
            configure_proxy
            ;;
        5)
            REWRITE_ENABLED=true
            configure_rewrite
            ;;
        6)
            COMPRESS_ENABLED=true
            configure_compress
            ;;
        7)
            SECDOWNLOAD_ENABLED=true
            configure_secdownload
            ;;
        8)
            STATUS_ENABLED=true
            configure_status
            ;;
        9)
            ACCESSLOG_ENABLED=true
            configure_accesslog
            ;;
        10)
            EVHOST_ENABLED=true
            configure_evhost
            ;;
        11)
            install_all_modules
            ;;
        12)
            echo -e "${YELLOW}Skipping module installation${NC}"
            ;;
        *)
            echo -e "${RED}Invalid choice${NC}"
            configure_modules
            ;;
    esac
}

# Install all recommended modules
install_all_modules() {
    echo -e "${CYAN}Installing all recommended modules...${NC}"
    
    FASTCGI_ENABLED=true
    SSL_ENABLED=true
    CACHE_ENABLED=true
    PROXY_ENABLED=true
    REWRITE_ENABLED=true
    COMPRESS_ENABLED=true
    STATUS_ENABLED=true
    ACCESSLOG_ENABLED=true
    EVHOST_ENABLED=true
    
    configure_fastcgi
    configure_ssl
    configure_cache
    configure_proxy
    configure_rewrite
    configure_compress
    configure_status
    configure_accesslog
    configure_evhost
    
    echo -e "${GREEN}✓ All recommended modules installed${NC}"
}

# Configure FastCGI
configure_fastcgi() {
    echo -e "${CYAN}Configuring FastCGI module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-fastcgi.conf" << 'EOF'
# FastCGI Configuration
server.modules += ("mod_fastcgi")

# PHP FastCGI
fastcgi.server = (
    ".php" => (
        "localhost" => (
            "socket" => "/run/php/php8.2-fpm.sock",
            "broken-scriptfilename" => "enable",
            "allow-x-send-file" => "enable"
        )
    )
)

# Python FastCGI (optional)
# fastcgi.server = (
#     ".py" => (
#         "python" => (
#             "socket" => "/run/python-fcgi.sock",
#             "bin-path" => "/usr/bin/python",
#             "max-procs" => 1,
#             "idle-timeout" => 20
#         )
#     )
# )
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-fastcgi.conf" "$CONFIG_DIR/conf-enabled/10-fastcgi.conf"
    echo -e "${GREEN}✓ FastCGI configured${NC}"
}

# Configure SSL
configure_ssl() {
    echo -e "${CYAN}Configuring SSL/TLS module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-ssl.conf" << 'EOF'
# SSL Configuration
server.modules += ("mod_openssl")

# SSL settings
$SERVER["socket"] == ":443" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/letsencrypt/live/domain.com/fullchain.pem"
    ssl.ca-file = "/etc/letsencrypt/live/domain.com/chain.pem"
    
    # SSL Security Configuration
    ssl.honor-cipher-order = "enable"
    ssl.use-sslv2 = "disable"
    ssl.use-sslv3 = "disable"
    ssl.use-tlsv1 = "disable"
    ssl.use-tlsv1.1 = "disable"
    
    # Modern cipher suites
    ssl.cipher-list = "ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384"
    
    # SSL Protocols
    ssl.openssl.ssl-conf-cmd = ("Protocol" => "-ALL, TLSv1.2, TLSv1.3")
    
    # HSTS
    setenv.add-response-header = (
        "Strict-Transport-Security" => "max-age=31536000; includeSubDomains"
    )
}

# Redirect HTTP to HTTPS
$HTTP["host"] =~ ".*" {
    url.redirect = (
        "^/(.*)" => "https://%0/$1"
    )
}
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-ssl.conf" "$CONFIG_DIR/conf-enabled/10-ssl.conf"
    echo -e "${GREEN}✓ SSL configured${NC}"
}

# Configure Cache
configure_cache() {
    echo -e "${CYAN}Configuring Cache module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-cache.conf" << 'EOF'
# Cache Configuration
server.modules += ("mod_cache")

# Cache settings
cache.enable = "enable"
cache.max-age = 3600
cache.debug = "disable"
cache.bases = ("/var/cache/lighttpd")

# Cache conditions
cache.supported-requests = ("GET", "HEAD")
cache.supported-status = (200, 301, 302)
cache.ignore-request = (
    "Cookie",
    "Authorization",
    "Set-Cookie"
)

# Cache specific file types
$HTTP["url"] =~ "\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$" {
    cache.max-age = 86400
    cache.enable = "enable"
}
EOF
    
    mkdir -p /var/cache/lighttpd
    ln -sf "$CONFIG_DIR/conf-available/10-cache.conf" "$CONFIG_DIR/conf-enabled/10-cache.conf"
    echo -e "${GREEN}✓ Cache configured${NC}"
}

# Configure Proxy
configure_proxy() {
    echo -e "${CYAN}Configuring Proxy module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-proxy.conf" << 'EOF'
# Proxy Configuration
server.modules += ("mod_proxy")

# Proxy settings
proxy.server = (
    "/api/" => (
        "backend" => (
            "host" => "127.0.0.1",
            "port" => 8080
        )
    ),
    "/app/" => (
        "backend" => (
            "host" => "127.0.0.1",
            "port" => 3000
        )
    )
)

# Proxy headers
proxy.header = (
    "map-urlpath" => (
        "/api/" => "/",
        "/app/" => "/"
    )
)
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-proxy.conf" "$CONFIG_DIR/conf-enabled/10-proxy.conf"
    echo -e "${GREEN}✓ Proxy configured${NC}"
}

# Configure Rewrite
configure_rewrite() {
    echo -e "${CYAN}Configuring Rewrite module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-rewrite.conf" << 'EOF'
# URL Rewrite Configuration
server.modules += ("mod_rewrite")

# Rewrite rules
url.rewrite-once = (
    "^/about$" => "/about.html",
    "^/contact$" => "/contact.html",
    "^/products/(.*)$" => "/product.php?id=$1",
    "^/blog/(.*)$" => "/blog.php?slug=$1",
    "^/user/([a-zA-Z0-9]+)$" => "/profile.php?username=$1"
)

# WordPress-like rules
url.rewrite-if-not-file = (
    "^/(wp-.+).*/?" => "$0",
    "^/(sitemap\.xml|robots\.txt)$" => "$0",
    "^/([^.]+)$" => "/index.php/$1"
)
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-rewrite.conf" "$CONFIG_DIR/conf-enabled/10-rewrite.conf"
    echo -e "${GREEN}✓ Rewrite configured${NC}"
}

# Configure Compression
configure_compress() {
    echo -e "${CYAN}Configuring Compression module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-compress.conf" << 'EOF'
# Compression Configuration
server.modules += ("mod_compress")

# Compression settings
compress.cache-dir = "/var/cache/lighttpd/compress"
compress.filetype = (
    "text/plain",
    "text/html",
    "text/css",
    "text/xml",
    "text/javascript",
    "application/javascript",
    "application/json",
    "application/xml",
    "application/rss+xml",
    "image/svg+xml"
)

# Enable deflate
compress.allowed-encodings = ("brotli", "gzip", "deflate")
EOF
    
    mkdir -p /var/cache/lighttpd/compress
    ln -sf "$CONFIG_DIR/conf-available/10-compress.conf" "$CONFIG_DIR/conf-enabled/10-compress.conf"
    echo -e "${GREEN}✓ Compression configured${NC}"
}

# Configure Secure Downloads
configure_secdownload() {
    echo -e "${CYAN}Configuring Secure Downloads module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-secdownload.conf" << 'EOF'
# Secure Downloads Configuration
server.modules += ("mod_secdownload")

# Secure download settings
secdownload.secret = "your-secret-key-here"
secdownload.document-root = "/var/www/downloads"
secdownload.uri-prefix = "/download/"
secdownload.timeout = 3600

# Example usage:
# Generate URL: /download/<hex-time>/<hex-md5>/<filename>
# Where hex-md5 = md5(secret-key + filepath + hex-time)
EOF
    
    mkdir -p /var/www/downloads
    ln -sf "$CONFIG_DIR/conf-available/10-secdownload.conf" "$CONFIG_DIR/conf-enabled/10-secdownload.conf"
    echo -e "${GREEN}✓ Secure Downloads configured${NC}"
}

# Configure Status
configure_status() {
    echo -e "${CYAN}Configuring Status module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-status.conf" << 'EOF'
# Status Configuration
server.modules += ("mod_status")

# Status page settings
status.status-url = "/server-status"
status.config-url = "/server-config"
status.statistics-url = "/server-stats"

# Restrict access to localhost
$HTTP["remoteip"] !~ "127\.0\.0\.1" {
    url.access-deny = ("", "/server-status", "/server-config", "/server-stats")
}
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-status.conf" "$CONFIG_DIR/conf-enabled/10-status.conf"
    echo -e "${GREEN}✓ Status configured${NC}"
}

# Configure Access Log
configure_accesslog() {
    echo -e "${CYAN}Configuring Access Log module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-accesslog.conf" << 'EOF'
# Enhanced Access Log Configuration
server.modules += ("mod_accesslog")

# Access log format
accesslog.filename = "/var/log/lighttpd/access.log"
accesslog.format = "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-Forwarded-For}i\""

# Custom log formats
accesslog.format += "%{Host}i %{Connection}i %{Cache-Control}i"

# Log rotation (handled by logrotate)
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-accesslog.conf" "$CONFIG_DIR/conf-enabled/10-accesslog.conf"
    echo -e "${GREEN}✓ Access Log configured${NC}"
}

# Configure Enhanced Virtual Hosting
configure_evhost() {
    echo -e "${CYAN}Configuring Enhanced Virtual Hosting module...${NC}"
    
    cat > "$CONFIG_DIR/conf-available/10-evhost.conf" << 'EOF'
# Enhanced Virtual Hosting Configuration
server.modules += ("mod_evhost")

# Virtual hosting pattern
# Directory structure: /var/www/vhosts/<domain>/www/
evhost.path-pattern = "/var/www/vhosts/%3/www/"

# Alternative patterns
# evhost.path-pattern = "/var/www/%0/"
# evhost.path-pattern = "/var/www/%3.%2.%1/www/"

# Error pages for virtual hosts
server.errorfile-prefix = "/var/www/vhosts/errorpages/"

# Custom error pages
server.error-handler-404 = "/errorpages/404.html"
server.error-handler-500 = "/errorpages/500.html"
EOF
    
    mkdir -p /var/www/vhosts
    mkdir -p /var/www/vhosts/errorpages
    ln -sf "$CONFIG_DIR/conf-available/10-evhost.conf" "$CONFIG_DIR/conf-enabled/10-evhost.conf"
    echo -e "${GREEN}✓ Enhanced Virtual Hosting configured${NC}"
}

# Create sample virtual host
create_sample_vhost() {
    echo -e "${CYAN}Creating sample virtual host...${NC}"
    
    cat > "$CONFIG_DIR/vhosts/default.conf" << 'EOF'
# Default Virtual Host
$HTTP["host"] =~ "^(www\.)?localhost$" {
    server.document-root = "/var/www/html"
    server.errorlog = "/var/log/lighttpd/localhost-error.log"
    accesslog.filename = "/var/log/lighttpd/localhost-access.log"
    
    # Directory listing
    dir-listing.activate = "enable"
    
    # Security headers
    setenv.add-response-header = (
        "X-Frame-Options" => "DENY",
        "X-Content-Type-Options" => "nosniff",
        "X-XSS-Protection" => "1; mode=block",
        "Referrer-Policy" => "strict-origin-when-cross-origin"
    )
}
EOF
    
    echo -e "${GREEN}✓ Sample virtual host created${NC}"
}

# Security hardening
security_hardening() {
    echo -e "${CYAN}Applying security hardening...${NC}"
    
    # Set proper permissions
    chown -R www-data:www-data "$WEB_ROOT"
    chown -R www-data:www-data "$LOG_DIR"
    chown -R root:root "$CONFIG_DIR"
    chmod 755 "$CONFIG_DIR"
    chmod 644 "$CONFIG_DIR"/*.conf
    chmod 750 "$LOG_DIR"
    
    # Create security configuration
    cat > "$CONFIG_DIR/conf-available/10-security.conf" << 'EOF'
# Security Configuration

# Hide server version
server.tag = "WebServer"

# Limit request size
server.max-request-size = 10485760

# Timeout settings
server.max-keep-alive-idle = 30
server.max-read-idle = 60
server.max-write-idle = 360

# Prevent clickjacking
setenv.add-response-header += (
    "X-Frame-Options" => "DENY"
)

# Prevent MIME type sniffing
setenv.add-response-header += (
    "X-Content-Type-Options" => "nosniff"
)

# XSS Protection
setenv.add-response-header += (
    "X-XSS-Protection" => "1; mode=block"
)

# Content Security Policy
setenv.add-response-header += (
    "Content-Security-Policy" => "default-src 'self'"
)

# Referrer Policy
setenv.add-response-header += (
    "Referrer-Policy" => "strict-origin-when-cross-origin"
)

# Block access to sensitive files
$HTTP["url"] =~ "\.(conf|log|sql|bak|backup|old)$" {
    url.access-deny = ("")
}

# Block access to hidden files
$HTTP["url"] =~ "/\." {
    url.access-deny = ("")
}
EOF
    
    ln -sf "$CONFIG_DIR/conf-available/10-security.conf" "$CONFIG_DIR/conf-enabled/10-security.conf"
    
    echo -e "${GREEN}✓ Security hardening applied${NC}"
}

# Create logrotate configuration
create_logrotate() {
    echo -e "${CYAN}Creating logrotate configuration...${NC}"
    
    cat > /etc/logrotate.d/lighttpd << 'EOF'
/var/log/lighttpd/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 www-data adm
    sharedscripts
    postrotate
        if [ -f /run/lighttpd/lighttpd.pid ]; then
            systemctl reload lighttpd
        fi
    endscript
}
EOF
    
    echo -e "${GREEN}✓ Logrotate configuration created${NC}"
}

# Create management tools
create_management_tools() {
    echo -e "${CYAN}Creating management tools...${NC}"
    
    # Lighttpd monitor
    cat > /usr/local/bin/lighttpd-monitor << 'EOF'
#!/bin/bash
# Lighttpd Monitoring Tool

echo "=================================="
echo "    Lighttpd Server Status      "
echo "=================================="

# Check if Lighttpd is running
if systemctl is-active --quiet lighttpd; then
    echo -e "Status: \e[32mRunning\e[0m"
else
    echo -e "Status: \e[31mStopped\e[0m"
fi

# Show version
if [ -f /opt/lighttpd/sbin/lighttpd ]; then
    echo "Version: $(/opt/lighttpd/sbin/lighttpd -v 2>&1 | head -n1)"
fi

# Show uptime
if [ -f /run/lighttpd/lighttpd.pid ]; then
    PID=$(cat /run/lighttpd/lighttpd.pid)
    if [ -n "$PID" ]; then
        echo "PID: $PID"
        echo "Uptime: $(ps -o etime= -p $PID | tr -d ' ')"
    fi
fi

# Show connections
echo "Active Connections: $(ss -tn state established '( dport = :http or dport = :https )' | wc -l)"

# Show memory usage
if [ -n "$PID" ]; then
    echo "Memory Usage: $(ps -o rss= -p $PID | tr -d ' ') KB"
fi

echo ""
echo "Recent Log Entries:"
tail -n 5 /var/log/lighttpd/error.log 2>/dev/null || echo "No error logs available"
EOF

    # Lighttpd reload
    cat > /usr/local/bin/lighttpd-reload << 'EOF'
#!/bin/bash
# Graceful Lighttpd Reload

if systemctl is-active --quiet lighttpd; then
    echo "Reloading Lighttpd configuration..."
    if systemctl reload lighttpd; then
        echo -e "\e[32m✓ Lighttpd reloaded successfully\e[0m"
    else
        echo -e "\e[31m✗ Failed to reload Lighttpd\e[0m"
        exit 1
    fi
else
    echo "Lighttpd is not running. Starting..."
    if systemctl start lighttpd; then
        echo -e "\e[32m✓ Lighttpd started successfully\e[0m"
    else
        echo -e "\e[31m✗ Failed to start Lighttpd\e[0m"
        exit 1
    fi
fi
EOF

    # Lighttpd backup
    cat > /usr/local/bin/lighttpd-backup << 'EOF'
#!/bin/bash
# Lighttpd Configuration Backup

BACKUP_DIR="/opt/lighttpd/backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$BACKUP_DIR/lighttpd-config-$TIMESTAMP.tar.gz"

echo "Creating Lighttpd configuration backup..."

mkdir -p "$BACKUP_DIR"

# Backup configuration files
tar -czf "$BACKUP_FILE" \
    /etc/lighttpd/ \
    /var/www/html/ \
    2>/dev/null

if [ $? -eq 0 ]; then
    echo -e "\e[32m✓ Backup created: $BACKUP_FILE\e[0m"
    
    # Keep only last 10 backups
    find "$BACKUP_DIR" -name "lighttpd-config-*.tar.gz" -type f | sort -r | tail -n +11 | xargs rm -f
else
    echo -e "\e[31m✗ Backup failed\e[0m"
    exit 1
fi
EOF

    # Make tools executable
    chmod +x /usr/local/bin/lighttpd-*
    
    echo -e "${GREEN}✓ Management tools created${NC}"
}

# Create test page
create_test_page() {
    echo -e "${CYAN}Creating test page...${NC}"
    
    cat > "$WEB_ROOT/index.html" << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lighttpd Server - Installation Complete!</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
        .header { text-align: center; color: #333; }
        .success { color: #28a745; }
        .info { background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .module { background: #e9ecef; padding: 10px; margin: 5px 0; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="success">🚀 Lighttpd Installation Complete!</h1>
        <p>Your high-performance web server is ready to serve content.</p>
    </div>
    
    <div class="info">
        <h2>📋 Server Information</h2>
        <p><strong>Server:</strong> Lighttpd</p>
        <p><strong>Document Root:</strong> /var/www/html</p>
        <p><strong>Configuration:</strong> /etc/lighttpd/</p>
        <p><strong>Logs:</strong> /var/log/lighttpd/</p>
    </div>
    
    <div class="info">
        <h2>🔧 Management Commands</h2>
        <p><code>lighttpd-monitor</code> - Check server status</p>
        <p><code>lighttpd-reload</code> - Reload configuration</p>
        <p><code>lighttpd-backup</code> - Backup configurations</p>
        <p><code>systemctl status lighttpd</code> - Service status</p>
    </div>
    
    <div class="info">
        <h2>🌟 Next Steps</h2>
        <p>1. Configure your virtual hosts in <code>/etc/lighttpd/vhosts/</code></p>
        <p>2. Set up SSL certificates with Let's Encrypt</p>
        <p>3. Configure PHP/FastCGI if needed</p>
        <p>4. Test your applications</p>
    </div>
    
    <div class="info">
        <h2>📊 Server Status</h2>
        <p><strong>Current Time:</strong> <script>document.write(new Date().toLocaleString());</script></p>
        <p><strong>Server Software:</strong> <?php echo $_SERVER['SERVER_SOFTWARE']; ?></p>
        <p><strong>Request Method:</strong> <?php echo $_SERVER['REQUEST_METHOD']; ?></p>
    </div>
</body>
</html>
EOF
    
    chown www-data:www-data "$WEB_ROOT/index.html"
    
    echo -e "${GREEN}✓ Test page created${NC}"
}

# Test configuration
test_configuration() {
    echo -e "${CYAN}Testing Lighttpd configuration...${NC}"
    
    # Test configuration syntax
    if "$INSTALL_DIR/sbin/lighttpd" -t -f "$CONFIG_DIR/lighttpd.conf"; then
        echo -e "${GREEN}✓ Configuration test passed${NC}"
    else
        echo -e "${RED}✗ Configuration test failed${NC}"
        return 1
    fi
}

# Start and enable Lighttpd
start_lighttpd() {
    echo -e "${CYAN}Starting Lighttpd service...${NC}"
    
    if systemctl start lighttpd; then
        echo -e "${GREEN}✓ Lighttpd started successfully${NC}"
    else
        echo -e "${RED}✗ Failed to start Lighttpd${NC}"
        return 1
    fi
    
    # Enable on boot
    systemctl enable lighttpd
    
    # Wait a moment for startup
    sleep 2
    
    # Check if running
    if systemctl is-active --quiet lighttpd; then
        echo -e "${GREEN}✓ Lighttpd is running${NC}"
    else
        echo -e "${RED}✗ Lighttpd failed to start${NC}"
        return 1
    fi
}

# Show completion message
show_completion() {
    echo ""
    echo "========================================"
    echo "  Lighttpd Installation Complete!     "
    echo "========================================"
    echo ""
    echo -e "${GREEN}Lighttpd Version: $LIGHTTPD_VERSION${NC}"
    echo -e "${GREEN}Installation Directory: $INSTALL_DIR${NC}"
    echo -e "${GREEN}Configuration Directory: $CONFIG_DIR${NC}"
    echo -e "${GREEN}Web Root: $WEB_ROOT${NC}"
    echo -e "${GREEN}Log Directory: $LOG_DIR${NC}"
    echo ""
    
    echo "🔧 Enabled Modules:"
    [[ "$FASTCGI_ENABLED" == true ]] && echo -e "   ${GREEN}✓ FastCGI (PHP/Python/Ruby support)${NC}"
    [[ "$SSL_ENABLED" == true ]] && echo -e "   ${GREEN}✓ SSL/TLS (HTTPS support)${NC}"
    [[ "$CACHE_ENABLED" == true ]] && echo -e "   ${GREEN}✓ Cache (Caching system)${NC}"
    [[ "$PROXY_ENABLED" == true ]] && echo -e "   ${GREEN}✓ Proxy (Reverse proxy)${NC}"
    [[ "$REWRITE_ENABLED" == true ]] && echo -e "   ${GREEN}✓ Rewrite (URL rewriting)${NC}"
    [[ "$COMPRESS_ENABLED" == true ]] && echo -e "   ${GREEN}✓ Compress (Compression)${NC}"
    [[ "$SECDOWNLOAD_ENABLED" == true ]] && echo -e "   ${GREEN}✓ SecDownload (Secure downloads)${NC}"
    [[ "$STATUS_ENABLED" == true ]] && echo -e "   ${GREEN}✓ Status (Server status)${NC}"
    [[ "$ACCESSLOG_ENABLED" == true ]] && echo -e "   ${GREEN}✓ AccessLog (Enhanced logging)${NC}"
    [[ "$EVHOST_ENABLED" == true ]] && echo -e "   ${GREEN}✓ EVHost (Enhanced virtual hosting)${NC}"
    
    echo ""
    echo "🔧 Management Commands:"
    echo -e "   ${CYAN}lighttpd-monitor${NC}    - Check server status"
    echo -e "   ${CYAN}lighttpd-reload${NC}     - Reload configuration"
    echo -e "   ${CYAN}lighttpd-backup${NC}     - Backup configurations"
    echo -e "   ${CYAN}systemctl status lighttpd${NC} - Service status"
    
    echo ""
    echo "🌐 Access your server:"
    echo -e "   ${CYAN}http://your-domain.com${NC} - Test page"
    [[ "$STATUS_ENABLED" == true ]] && echo -e "   ${CYAN}http://your-domain.com/server-status${NC} - Server status"
    
    echo ""
    echo "📁 Important Files:"
    echo -e "   ${CYAN}$CONFIG_DIR/lighttpd.conf${NC} - Main configuration"
    echo -e "   ${CYAN}$CONFIG_DIR/vhosts/${NC} - Virtual hosts"
    echo -e "   ${CYAN}$LOG_DIR/error.log${NC} - Error log"
    echo -e "   ${CYAN}$LOG_DIR/access.log${NC} - Access log"
    
    echo ""
    echo "🔒 Security Features Applied:"
    echo -e "   ${GREEN}✓ Secure file permissions${NC}"
    echo -e "   ${GREEN}✓ Security headers${NC}"
    echo -e "   ${GREEN}✓ Server version hidden${NC}"
    echo -e "   ${GREEN}✓ Request size limits${NC}"
    echo -e "   ${GREEN}✓ Access restrictions${NC}"
    
    echo ""
    echo "🎯 Next Steps:"
    echo "   1. Configure your virtual hosts"
    echo "   2. Set up SSL certificates"
    echo "   3. Deploy your applications"
    echo "   4. Monitor server performance"
    
    echo ""
    echo -e "${GREEN}🎉 Lighttpd is ready for production use!${NC}"
}

# Main installation function
main() {
    echo "========================================"
    echo "    Lighttpd Web Server Installer      "
    echo "========================================"
    echo ""
    
    check_root
    detect_os
    get_lighttpd_version
    install_dependencies
    install_lighttpd_core
    create_directories
    create_main_config
    configure_modules
    create_sample_vhost
    security_hardening
    create_logrotate
    create_management_tools
    create_test_page
    test_configuration
    start_lighttpd
    show_completion
}

# Run main function
main "$@" 2>&1 | tee "$LOG_FILE"
